apiVersion: v1
kind: Service
metadata:
  name: node-hostname
spec:
  selector:
    app: node-hostname
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hostname
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-hostname
  template:
    metadata:
      labels:
        app: node-hostname
    spec:
      containers:
        - name: app
          image: localhost:5000/node_hostname
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
